@startuml
package View {
    component "React Page" as hp
    component "Search Components" as sp

    hp --> sp : component
}

package Controller {
    component SearchController
}

package Model {
    component SearchModel as sm
    component SearchModelServlet as sms

    sms --( SearchModelInterface
    SearchModelInterface -- sm
}

package Database {
    frame "Entity" {
        [database]
    }
}

interface HTTPS as h2

[sp] --( SearchControllerInterface
SearchControllerInterface -- SearchController

SearchController ..> h2 : uses
h2 -- [sms]


sm -- database
@enduml