@startuml
skinparam packageStyle rectangle
left to right direction
actor Seller
actor Administrator
rectangle accountManagement {
Seller --> (Logs into seller account)
Seller -> (Creates a seller account)
Administrator --> (Logs into administrator account)
(Creates a seller account) -> (Logs into seller account)
}

rectangle sellerActions {
note "must be in at least one seller group" as N1

(Logs into seller account) -->(Create Fixed Price Listing)
(Create Fixed Price Listing) -.> (Create Fixed Price Listing for Individual):include
(Create Fixed Price Listing) -.> (Create Fixed Price Listing for Seller Group):include
(Create Fixed Price Listing for Seller Group) .. (N1)

(Logs into seller account) --> (Create Auction Listing)
(Create Auction Listing) -.> (Create Auction Listing for Individual):include

(Create Auction Listing) -.> (Create Auction Listing for Seller Group): include
(Create Auction Listing for Seller Group) .. (N1)

(Logs into seller account) --> (Creates a seller group)
(Logs into seller account) --> (Sends invites to authenticated sellers)
(Logs into seller account) -> (Receives invite to seller group)
(Logs into seller account) -> (Views a list of active orders)
(Views a list of active orders) -.> (Modify quantity of selected order):extend
(Views a list of active orders) -.> (Cancel Order):extend



}

rectangle administratorActions {
    (Logs into administrator account) --> (View all listings)
    (Logs into administrator account) --> (View all users)
    (Logs into administrator account) --> (View all active orders)
    (View all active orders) -.> (Close an active order):extend
    (View all users) -.> (View customer order history):extend
    (View all listings) -.> (Remove listing):extend
    (View all listings) -.> (Modify listing information):extend
}

@enduml