@startuml

'Admin class
class Admin<? extends User> {
    - userRoles : UserRoles
    - sellerGroupList : List<SellerGroup>
    - userGroupList : List<User>
    {method} + getAllPurchases() : List<OrderItem>
    {method} + getAllSellerGroup(repo : IUnitofWork ) : List<SellerGroup>
    {method} + getAllUsers() : List<User>
    {method} + createSellerGroup(groupName : String) : List<SellerGroup>
    {method} + addSellerToGroup(groupName : String, userId : int) : GroupMembership
    {method} + removeSellerFromGroup(groupName : String, userId : int) : GroupMembership
    {method} + removeListing(listingId : int) : Listing
}
'AuctionListing class
class AuctionListing<? extends Listing> {
    {method} + bid(bid : Money, bidTime : localDateTime, userId : int): Bid
}
'Bid Class
class Bid<? extends EntityObject> {
    - listingId : int
    - userId : int
    - bidAmount : Money
    {method} {static} + create(listingId : int, userId : int, bidAmount : Money) : Bid

}
'Customer Class
class Customer <? extends User> {
    - userRoles: UserRoles
    - listingList : List<Listing>
    {method} + checkoutListing(address : String,  oiList : List<OrderItem>) : Order
    {method} + bid(listingId : int, bidAmount : Money) : Bid
    {method} + viewAllOrders() : List<Order>
    {method} + modifyOrder(orderId : int, listingId : int, quantity : int) : List<EntityObject>
    {method} + cancelOrder(orderId : int) : Order
}
'Filter Class
'FixedPriceListing Class
'
@enduml