@startuml


/' Servlet Classes

/' Bid Servlet
class BidServlet <extends HttpServlet> {
    /' Bid Servlet creates new bids.
    /' Bid Servlet makes use of UnitofWork.


}
/' CancelOrderServlet

/' CheckoutServlet
/' CreateListingServlet
/' CreateSellerGroupServlet
/' DeleteListingServlet
/' GetAllPurchasesServlet
/' GetAllSellerGroupServlet
/' GetAllUsersServlet
/' LoginServlet
/' ModifyServlet
/' RegisterUserServlet
/' SearchServlet
/' SellerOnboardServlet
/' SellerRemovalServlet
/' ViewOrderServlet


@enduml